// Generated by https://quicktype.io

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Metadata
    {
        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("image")]
        public string Image { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }
    }

    public partial class Metadata
    {
        public static Metadata FromJson(string json) => JsonConvert.DeserializeObject<Metadata>(json, QuickType.Converter.Settings);
    }
}
