// Generated by https://quicktype.io

using System;
using System.Collections.Generic;

using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace QuickType
{
    public partial class MoralisResponse
    {
        [JsonProperty("total")]
        public long Total { get; set; }

        [JsonProperty("page")]
        public long Page { get; set; }

        [JsonProperty("page_size")]
        public long PageSize { get; set; }

        [JsonProperty("cursor")]
        public string Cursor { get; set; }

        [JsonProperty("result")]
        public Result[] Result { get; set; }

        [JsonProperty("status")]
        public string Status { get; set; }
    }

    public partial class Result
    {
        [JsonProperty("token_address")]
        public string TokenAddress { get; set; }

        [JsonProperty("token_id")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long TokenId { get; set; }

        [JsonProperty("block_number_minted")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long BlockNumberMinted { get; set; }

        [JsonProperty("owner_of")]
        public string OwnerOf { get; set; }

        [JsonProperty("block_number")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long BlockNumber { get; set; }

        [JsonProperty("amount")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Amount { get; set; }

        [JsonProperty("contract_type")]
        public string ContractType { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("symbol")]
        public string Symbol { get; set; }

        [JsonProperty("token_uri")]
        public Uri TokenUri { get; set; }

        [JsonProperty("metadata")]
        public string Metadata { get; set; }

        [JsonProperty("synced_at")]
        public DateTimeOffset SyncedAt { get; set; }

        [JsonProperty("is_valid")]
        public long IsValid { get; set; }

        [JsonProperty("syncing")]
        public long Syncing { get; set; }

        [JsonProperty("frozen")]
        public long Frozen { get; set; }
    }

    public partial class MoralisResponse
    {
        public static MoralisResponse FromJson(string json) => JsonConvert.DeserializeObject<MoralisResponse>(json, QuickType.Converter.Settings);
    }
}